/**
 * This file is generated by i18next-resources-for-ts
 */
interface Resources {
  "home-page": {
    "title": "The Game DB"
  },
  "languages": {
    "en": "English",
    "ru": "Русский"
  }
}

export default Resources;
