/**
 * This file is generated by i18next-resources-for-ts, command 'npm run gen-i18n'
 */
interface Resources {
  "components-page": {
    "title": "Components"
  },
  "creators-page": {
    "title": "Creators"
  },
  "games-page": {
    "title": "The Game DB"
  },
  "languages": {
    "en": "English",
    "ru": "Русский"
  },
  "select": {
    "loading": "Loading...",
    "no-options": "No options",
    "select": "Select..."
  }
}

export default Resources;
